services:
  web:
    build:
      context: ./web
      dockerfile: web.dockerfile
    volumes:
      - ./web:/app
    ports:
      - '3000:3000'
      - '5555:5555'
      - '6006:6006'
    depends_on:
      - db
    tty: true
    # 初回のみ実行
    # command: sh -c "npx prisma migrate deploy &&
    #                 node src/lib/prisma/pushClusterData.js &&
    #                 node src/lib/prisma/pushData.js &&
    #                 node src/lib/prisma/pushObjectWord.js &&
    #                 node src/lib/prisma/pushPosterToWord.js &&
    #                 node src/lib/prisma/pushTitleSim.js &&
    #                 npm run dev"

    # 2回目以降
    command: sh -c "npm run dev"

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - '5430:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/ssl:/etc/nginx/ssl
    tty: true
    depends_on:
      - web
