services:
  web:
    build:
      context: ./web
      dockerfile: web.dockerfile
    ports:
      - '8101:8000'
    volumes:
      - ./web:/app
    depends_on:
      - db
    tty: true
    command: sh -c "npm run build && npm run start -p 8000"

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - '5433:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d