services:
  web:
    build:
      context: ./web
      dockerfile: web.dockerfile
    volumes:
      - ./web:/app
    ports:
      - '8000:8000'
      - '6006:6006'
      - '5555:5555'
    depends_on:
      - db
    tty: true
    # command: sh -c "npm run dev"

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - '5430:5430'
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
