/*
  Warnings:

  - You are about to drop the column `discription` on the `posters` table. All the data in the column will be lost.
  - You are about to drop the `title_similarity_matrix` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `title_similarity_matrix_part1` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `title_similarity_matrix_part2` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `title_similarity_matrix_part3` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "title_similarity_matrix_part1" DROP CONSTRAINT "title_similarity_matrix_part1_similarity_matrix_id_fkey";

-- DropForeignKey
ALTER TABLE "title_similarity_matrix_part2" DROP CONSTRAINT "title_similarity_matrix_part2_similarity_matrix_id_fkey";

-- DropForeignKey
ALTER TABLE "title_similarity_matrix_part3" DROP CONSTRAINT "title_similarity_matrix_part3_similarity_matrix_id_fkey";

-- AlterTable
ALTER TABLE "posters" DROP COLUMN "discription",
ADD COLUMN     "description" TEXT;

-- DropTable
DROP TABLE "title_similarity_matrix";

-- DropTable
DROP TABLE "title_similarity_matrix_part1";

-- DropTable
DROP TABLE "title_similarity_matrix_part2";

-- DropTable
DROP TABLE "title_similarity_matrix_part3";

-- CreateTable
CREATE TABLE "title_similarities" (
    "id" TEXT NOT NULL,
    "sim_1" TEXT,
    "sim_2" TEXT,
    "sim_3" TEXT,
    "sim_4" TEXT,
    "sim_5" TEXT,
    "sim_6" TEXT,
    "sim_7" TEXT,
    "sim_8" TEXT,
    "sim_9" TEXT,
    "sim_10" TEXT,
    "sim_11" TEXT,
    "sim_12" TEXT,
    "sim_13" TEXT,
    "sim_14" TEXT,
    "sim_15" TEXT,
    "sim_16" TEXT,
    "sim_17" TEXT,
    "sim_18" TEXT,
    "sim_19" TEXT,
    "sim_20" TEXT,
    "sim_21" TEXT,
    "sim_22" TEXT,
    "sim_23" TEXT,
    "sim_24" TEXT,
    "sim_25" TEXT,
    "sim_26" TEXT,
    "sim_27" TEXT,
    "sim_28" TEXT,
    "sim_29" TEXT,
    "sim_30" TEXT,
    "sim_31" TEXT,
    "sim_32" TEXT,
    "sim_33" TEXT,
    "sim_34" TEXT,
    "sim_35" TEXT,
    "sim_36" TEXT,
    "sim_37" TEXT,
    "sim_38" TEXT,
    "sim_39" TEXT,
    "sim_40" TEXT,
    "sim_41" TEXT,
    "sim_42" TEXT,
    "sim_43" TEXT,
    "sim_44" TEXT,
    "sim_45" TEXT,
    "sim_46" TEXT,
    "sim_47" TEXT,
    "sim_48" TEXT,
    "sim_49" TEXT,
    "sim_50" TEXT,
    "sim_51" TEXT,
    "sim_52" TEXT,
    "sim_53" TEXT,
    "sim_54" TEXT,
    "sim_55" TEXT,
    "sim_56" TEXT,
    "sim_57" TEXT,
    "sim_58" TEXT,
    "sim_59" TEXT,
    "sim_60" TEXT,
    "sim_61" TEXT,
    "sim_62" TEXT,
    "sim_63" TEXT,
    "sim_64" TEXT,
    "sim_65" TEXT,
    "sim_66" TEXT,
    "sim_67" TEXT,
    "sim_68" TEXT,
    "sim_69" TEXT,
    "sim_70" TEXT,
    "sim_71" TEXT,
    "sim_72" TEXT,
    "sim_73" TEXT,
    "sim_74" TEXT,
    "sim_75" TEXT,
    "sim_76" TEXT,
    "sim_77" TEXT,
    "sim_78" TEXT,
    "sim_79" TEXT,
    "sim_80" TEXT,
    "sim_81" TEXT,
    "sim_82" TEXT,
    "sim_83" TEXT,
    "sim_84" TEXT,
    "sim_85" TEXT,
    "sim_86" TEXT,
    "sim_87" TEXT,
    "sim_88" TEXT,
    "sim_89" TEXT,
    "sim_90" TEXT,
    "sim_91" TEXT,
    "sim_92" TEXT,
    "sim_93" TEXT,
    "sim_94" TEXT,
    "sim_95" TEXT,
    "sim_96" TEXT,
    "sim_97" TEXT,
    "sim_98" TEXT,
    "sim_99" TEXT,
    "sim_100" TEXT,
    "sim_101" TEXT,
    "sim_102" TEXT,
    "sim_103" TEXT,
    "sim_104" TEXT,
    "sim_105" TEXT,
    "sim_106" TEXT,
    "sim_107" TEXT,
    "sim_108" TEXT,
    "sim_109" TEXT,
    "sim_110" TEXT,
    "sim_111" TEXT,
    "sim_112" TEXT,
    "sim_113" TEXT,
    "sim_114" TEXT,
    "sim_115" TEXT,
    "sim_116" TEXT,
    "sim_117" TEXT,
    "sim_118" TEXT,
    "sim_119" TEXT,
    "sim_120" TEXT,
    "sim_121" TEXT,
    "sim_122" TEXT,
    "sim_123" TEXT,
    "sim_124" TEXT,
    "sim_125" TEXT,
    "sim_126" TEXT,
    "sim_127" TEXT,
    "sim_128" TEXT,
    "sim_129" TEXT,
    "sim_130" TEXT,
    "sim_131" TEXT,
    "sim_132" TEXT,
    "sim_133" TEXT,
    "sim_134" TEXT,
    "sim_135" TEXT,
    "sim_136" TEXT,
    "sim_137" TEXT,
    "sim_138" TEXT,
    "sim_139" TEXT,
    "sim_140" TEXT,
    "sim_141" TEXT,
    "sim_142" TEXT,
    "sim_143" TEXT,
    "sim_144" TEXT,
    "sim_145" TEXT,
    "sim_146" TEXT,
    "sim_147" TEXT,
    "sim_148" TEXT,
    "sim_149" TEXT,
    "sim_150" TEXT,
    "sim_151" TEXT,
    "sim_152" TEXT,
    "sim_153" TEXT,
    "sim_154" TEXT,
    "sim_155" TEXT,
    "sim_156" TEXT,
    "sim_157" TEXT,
    "sim_158" TEXT,
    "sim_159" TEXT,
    "sim_160" TEXT,
    "sim_161" TEXT,
    "sim_162" TEXT,
    "sim_163" TEXT,
    "sim_164" TEXT,
    "sim_165" TEXT,
    "sim_166" TEXT,
    "sim_167" TEXT,
    "sim_168" TEXT,
    "sim_169" TEXT,
    "sim_170" TEXT,
    "sim_171" TEXT,
    "sim_172" TEXT,
    "sim_173" TEXT,
    "sim_174" TEXT,
    "sim_175" TEXT,
    "sim_176" TEXT,
    "sim_177" TEXT,
    "sim_178" TEXT,
    "sim_179" TEXT,
    "sim_180" TEXT,
    "sim_181" TEXT,
    "sim_182" TEXT,
    "sim_183" TEXT,
    "sim_184" TEXT,
    "sim_185" TEXT,
    "sim_186" TEXT,
    "sim_187" TEXT,
    "sim_188" TEXT,
    "sim_189" TEXT,
    "sim_190" TEXT,
    "sim_191" TEXT,
    "sim_192" TEXT,
    "sim_193" TEXT,
    "sim_194" TEXT,
    "sim_195" TEXT,
    "sim_196" TEXT,
    "sim_197" TEXT,
    "sim_198" TEXT,
    "sim_199" TEXT,
    "sim_200" TEXT,

    CONSTRAINT "title_similarities_pkey" PRIMARY KEY ("id")
);
