/*
  Warnings:

  - You are about to drop the `title_similarity_matrix` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `title_similarity_matrix_part1` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `title_similarity_matrix_part2` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `title_similarity_matrix_part3` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "title_similarity_matrix_part1" DROP CONSTRAINT "title_similarity_matrix_part1_similarity_matrix_id_fkey";

-- DropForeignKey
ALTER TABLE "title_similarity_matrix_part2" DROP CONSTRAINT "title_similarity_matrix_part2_similarity_matrix_id_fkey";

-- DropForeignKey
ALTER TABLE "title_similarity_matrix_part3" DROP CONSTRAINT "title_similarity_matrix_part3_similarity_matrix_id_fkey";

-- DropTable
DROP TABLE "title_similarity_matrix";

-- DropTable
DROP TABLE "title_similarity_matrix_part1";

-- DropTable
DROP TABLE "title_similarity_matrix_part2";

-- DropTable
DROP TABLE "title_similarity_matrix_part3";

-- CreateTable
CREATE TABLE "title_similarities" (
    "id" TEXT NOT NULL,
    "sim_1" TEXT NOT NULL,
    "sim_2" TEXT NOT NULL,
    "sim_3" TEXT NOT NULL,
    "sim_4" TEXT NOT NULL,
    "sim_5" TEXT NOT NULL,
    "sim_6" TEXT NOT NULL,
    "sim_7" TEXT NOT NULL,
    "sim_8" TEXT NOT NULL,
    "sim_9" TEXT NOT NULL,
    "sim_10" TEXT NOT NULL,
    "sim_11" TEXT NOT NULL,
    "sim_12" TEXT NOT NULL,
    "sim_13" TEXT NOT NULL,
    "sim_14" TEXT NOT NULL,
    "sim_15" TEXT NOT NULL,
    "sim_16" TEXT NOT NULL,
    "sim_17" TEXT NOT NULL,
    "sim_18" TEXT NOT NULL,
    "sim_19" TEXT NOT NULL,
    "sim_20" TEXT NOT NULL,
    "sim_21" TEXT NOT NULL,
    "sim_22" TEXT NOT NULL,
    "sim_23" TEXT NOT NULL,
    "sim_24" TEXT NOT NULL,
    "sim_25" TEXT NOT NULL,
    "sim_26" TEXT NOT NULL,
    "sim_27" TEXT NOT NULL,
    "sim_28" TEXT NOT NULL,
    "sim_29" TEXT NOT NULL,
    "sim_30" TEXT NOT NULL,
    "sim_31" TEXT NOT NULL,
    "sim_32" TEXT NOT NULL,
    "sim_33" TEXT NOT NULL,
    "sim_34" TEXT NOT NULL,
    "sim_35" TEXT NOT NULL,
    "sim_36" TEXT NOT NULL,
    "sim_37" TEXT NOT NULL,
    "sim_38" TEXT NOT NULL,
    "sim_39" TEXT NOT NULL,
    "sim_40" TEXT NOT NULL,
    "sim_41" TEXT NOT NULL,
    "sim_42" TEXT NOT NULL,
    "sim_43" TEXT NOT NULL,
    "sim_44" TEXT NOT NULL,
    "sim_45" TEXT NOT NULL,
    "sim_46" TEXT NOT NULL,
    "sim_47" TEXT NOT NULL,
    "sim_48" TEXT NOT NULL,
    "sim_49" TEXT NOT NULL,
    "sim_50" TEXT NOT NULL,
    "sim_51" TEXT NOT NULL,
    "sim_52" TEXT NOT NULL,
    "sim_53" TEXT NOT NULL,
    "sim_54" TEXT NOT NULL,
    "sim_55" TEXT NOT NULL,
    "sim_56" TEXT NOT NULL,
    "sim_57" TEXT NOT NULL,
    "sim_58" TEXT NOT NULL,
    "sim_59" TEXT NOT NULL,
    "sim_60" TEXT NOT NULL,
    "sim_61" TEXT NOT NULL,
    "sim_62" TEXT NOT NULL,
    "sim_63" TEXT NOT NULL,
    "sim_64" TEXT NOT NULL,
    "sim_65" TEXT NOT NULL,
    "sim_66" TEXT NOT NULL,
    "sim_67" TEXT NOT NULL,
    "sim_68" TEXT NOT NULL,
    "sim_69" TEXT NOT NULL,
    "sim_70" TEXT NOT NULL,
    "sim_71" TEXT NOT NULL,
    "sim_72" TEXT NOT NULL,
    "sim_73" TEXT NOT NULL,
    "sim_74" TEXT NOT NULL,
    "sim_75" TEXT NOT NULL,
    "sim_76" TEXT NOT NULL,
    "sim_77" TEXT NOT NULL,
    "sim_78" TEXT NOT NULL,
    "sim_79" TEXT NOT NULL,
    "sim_80" TEXT NOT NULL,
    "sim_81" TEXT NOT NULL,
    "sim_82" TEXT NOT NULL,
    "sim_83" TEXT NOT NULL,
    "sim_84" TEXT NOT NULL,
    "sim_85" TEXT NOT NULL,
    "sim_86" TEXT NOT NULL,
    "sim_87" TEXT NOT NULL,
    "sim_88" TEXT NOT NULL,
    "sim_89" TEXT NOT NULL,
    "sim_90" TEXT NOT NULL,
    "sim_91" TEXT NOT NULL,
    "sim_92" TEXT NOT NULL,
    "sim_93" TEXT NOT NULL,
    "sim_94" TEXT NOT NULL,
    "sim_95" TEXT NOT NULL,
    "sim_96" TEXT NOT NULL,
    "sim_97" TEXT NOT NULL,
    "sim_98" TEXT NOT NULL,
    "sim_99" TEXT NOT NULL,
    "sim_100" TEXT NOT NULL,
    "sim_101" TEXT NOT NULL,
    "sim_102" TEXT NOT NULL,
    "sim_103" TEXT NOT NULL,
    "sim_104" TEXT NOT NULL,
    "sim_105" TEXT NOT NULL,
    "sim_106" TEXT NOT NULL,
    "sim_107" TEXT NOT NULL,
    "sim_108" TEXT NOT NULL,
    "sim_109" TEXT NOT NULL,
    "sim_110" TEXT NOT NULL,
    "sim_111" TEXT NOT NULL,
    "sim_112" TEXT NOT NULL,
    "sim_113" TEXT NOT NULL,
    "sim_114" TEXT NOT NULL,
    "sim_115" TEXT NOT NULL,
    "sim_116" TEXT NOT NULL,
    "sim_117" TEXT NOT NULL,
    "sim_118" TEXT NOT NULL,
    "sim_119" TEXT NOT NULL,
    "sim_120" TEXT NOT NULL,
    "sim_121" TEXT NOT NULL,
    "sim_122" TEXT NOT NULL,
    "sim_123" TEXT NOT NULL,
    "sim_124" TEXT NOT NULL,
    "sim_125" TEXT NOT NULL,
    "sim_126" TEXT NOT NULL,
    "sim_127" TEXT NOT NULL,
    "sim_128" TEXT NOT NULL,
    "sim_129" TEXT NOT NULL,
    "sim_130" TEXT NOT NULL,
    "sim_131" TEXT NOT NULL,
    "sim_132" TEXT NOT NULL,
    "sim_133" TEXT NOT NULL,
    "sim_134" TEXT NOT NULL,
    "sim_135" TEXT NOT NULL,
    "sim_136" TEXT NOT NULL,
    "sim_137" TEXT NOT NULL,
    "sim_138" TEXT NOT NULL,
    "sim_139" TEXT NOT NULL,
    "sim_140" TEXT NOT NULL,
    "sim_141" TEXT NOT NULL,
    "sim_142" TEXT NOT NULL,
    "sim_143" TEXT NOT NULL,
    "sim_144" TEXT NOT NULL,
    "sim_145" TEXT NOT NULL,
    "sim_146" TEXT NOT NULL,
    "sim_147" TEXT NOT NULL,
    "sim_148" TEXT NOT NULL,
    "sim_149" TEXT NOT NULL,
    "sim_150" TEXT NOT NULL,
    "sim_151" TEXT NOT NULL,
    "sim_152" TEXT NOT NULL,
    "sim_153" TEXT NOT NULL,
    "sim_154" TEXT NOT NULL,
    "sim_155" TEXT NOT NULL,
    "sim_156" TEXT NOT NULL,
    "sim_157" TEXT NOT NULL,
    "sim_158" TEXT NOT NULL,
    "sim_159" TEXT NOT NULL,
    "sim_160" TEXT NOT NULL,
    "sim_161" TEXT NOT NULL,
    "sim_162" TEXT NOT NULL,
    "sim_163" TEXT NOT NULL,
    "sim_164" TEXT NOT NULL,
    "sim_165" TEXT NOT NULL,
    "sim_166" TEXT NOT NULL,
    "sim_167" TEXT NOT NULL,
    "sim_168" TEXT NOT NULL,
    "sim_169" TEXT NOT NULL,
    "sim_170" TEXT NOT NULL,
    "sim_171" TEXT NOT NULL,
    "sim_172" TEXT NOT NULL,
    "sim_173" TEXT NOT NULL,
    "sim_174" TEXT NOT NULL,
    "sim_175" TEXT NOT NULL,
    "sim_176" TEXT NOT NULL,
    "sim_177" TEXT NOT NULL,
    "sim_178" TEXT NOT NULL,
    "sim_179" TEXT NOT NULL,
    "sim_180" TEXT NOT NULL,
    "sim_181" TEXT NOT NULL,
    "sim_182" TEXT NOT NULL,
    "sim_183" TEXT NOT NULL,
    "sim_184" TEXT NOT NULL,
    "sim_185" TEXT NOT NULL,
    "sim_186" TEXT NOT NULL,
    "sim_187" TEXT NOT NULL,
    "sim_188" TEXT NOT NULL,
    "sim_189" TEXT NOT NULL,
    "sim_190" TEXT NOT NULL,
    "sim_191" TEXT NOT NULL,
    "sim_192" TEXT NOT NULL,
    "sim_193" TEXT NOT NULL,
    "sim_194" TEXT NOT NULL,
    "sim_195" TEXT NOT NULL,
    "sim_196" TEXT NOT NULL,
    "sim_197" TEXT NOT NULL,
    "sim_198" TEXT NOT NULL,
    "sim_199" TEXT NOT NULL,
    "sim_200" TEXT NOT NULL,

    CONSTRAINT "title_similarities_pkey" PRIMARY KEY ("id")
);
